version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  default: all

  disable:
    - copyloopvar
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - intrange
    - lll
    - mnd
    - noinlineerr
    - paralleltest
    - wsl

  settings:
    goheader:
      template: |-
        Copyright Josh Komoroske. All rights reserved.
        Use of this source code is governed by the MIT license,
        a copy of which can be found in the LICENSE.txt file.
        SPDX-License-Identifier: MIT
