name: GolangCI-Lint
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "master"

jobs:
  lint:
    name: GolangCI-Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # https://github.com/golangci/golangci-lint/releases/tag/v2.2.2
          version: v2.2.2
